### ISSUE TITLE
Can I pass performance data?

### ISSUE THREAD

**Issue by bhavinajmera** [djmitche/pynsca#17]
Hi, Could please help me with passing performance data syntax.

**Comment by jantman** [comment]
As far as I know performance data isn't anything "special", it's just part of the plugin output string. See the [Nagios Plugin Development Guidelines](https://nagios-plugins.org/doc/guidelines.html#AEN33) for further information. As far as I know, there's nothing special about NSCA, you just need to pass the output as any plugin would.
